// Generated by https://quicktype.io

export interface About {
  name: string;
  image: string;
  description: string;
  social: Social;
}

export interface Social {
  fb: string;
  tw: string;
  ln: string;
  in: string;
}
